comments:
  allowedFields: ["name", "title", "description"]
  requiredFields: ["name", "title", "description"]
  format: "yaml"
  path: "_data/comments"
  branch: "main"
  generatedFields:
    date:
      type: date
      options:
        format: iso8601

